"""add_attribution_tables

Revision ID: 29e392128bad
Revises: e7846b8acf35
Create Date: 2026-02-21 21:25:13.769292

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29e392128bad"
down_revision: str | Sequence[str] | None = "e7846b8acf35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_value", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("manual_pct", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("priority", name="uq_allocation_rule_priority"),
    )
    op.create_table(
        "tenant_attributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("pct_of_total", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("mom_delta_usd", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("top_service_category", sa.String(length=255), nullable=True),
        sa.Column("allocated_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("tagged_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "year", "month", name="uq_tenant_attribution_key"),
    )
    op.create_index("idx_attribution_tenant_id", "tenant_attributions", ["tenant_id"], unique=False)
    op.create_index(
        "idx_attribution_year_month", "tenant_attributions", ["year", "month"], unique=False
    )
    op.create_table(
        "tenant_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("is_new", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenant_profiles")
    op.drop_index("idx_attribution_year_month", table_name="tenant_attributions")
    op.drop_index("idx_attribution_tenant_id", table_name="tenant_attributions")
    op.drop_table("tenant_attributions")
    op.drop_table("allocation_rules")
    # ### end Alembic commands ###
