"""add_anomalies_table

Revision ID: 37031473bbfa
Revises: 50f4678d8591
Create Date: 2026-02-21 09:53:48.157573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37031473bbfa'
down_revision: Union[str, Sequence[str], None] = '50f4678d8591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('resource_group', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='new'),
    sa.Column('expected', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('baseline_daily_avg', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('current_daily_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pct_deviation', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_monthly_impact', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name', 'resource_group', 'detected_date', name='uq_anomaly_key')
    )
    op.create_index('idx_anomaly_detected_date', 'anomalies', ['detected_date'], unique=False)
    op.create_index('idx_anomaly_severity', 'anomalies', ['severity'], unique=False)
    op.create_index('idx_anomaly_status', 'anomalies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_anomaly_status', table_name='anomalies')
    op.drop_index('idx_anomaly_severity', table_name='anomalies')
    op.drop_index('idx_anomaly_detected_date', table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
