"""add_cost_monitoring_columns

Revision ID: 50f4678d8591
Revises: 55bda49dc4a2
Create Date: 2026-02-21 06:56:38.662609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f4678d8591'
down_revision: Union[str, Sequence[str], None] = '55bda49dc4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_records', sa.Column('region', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('billing_records', sa.Column('tag', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('billing_records', sa.Column('resource_id', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('billing_records', sa.Column('resource_name', sa.String(length=500), nullable=False, server_default=''))
    op.create_index('idx_billing_region', 'billing_records', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_billing_region', table_name='billing_records')
    op.drop_column('billing_records', 'resource_name')
    op.drop_column('billing_records', 'resource_id')
    op.drop_column('billing_records', 'tag')
    op.drop_column('billing_records', 'region')
    # ### end Alembic commands ###
