"""billing_ingestion_tables

Revision ID: 55bda49dc4a2
Revises: d89aaf4be42d
Create Date: 2026-02-20 16:54:57.106112

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55bda49dc4a2"
down_revision: str | Sequence[str] | None = "d89aaf4be42d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("subscription_id", sa.String(length=255), nullable=False),
        sa.Column("resource_group", sa.String(length=255), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("meter_category", sa.String(length=255), nullable=False),
        sa.Column("pre_tax_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "usage_date",
            "subscription_id",
            "resource_group",
            "service_name",
            "meter_category",
            name="uq_billing_record_key",
        ),
    )
    op.create_index(
        "idx_billing_resource_group", "billing_records", ["resource_group"], unique=False
    )
    op.create_index("idx_billing_service_name", "billing_records", ["service_name"], unique=False)
    op.create_index(
        "idx_billing_subscription", "billing_records", ["subscription_id"], unique=False
    )
    op.create_index("idx_billing_usage_date", "billing_records", ["usage_date"], unique=False)
    op.create_table(
        "ingestion_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_by", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ingestion_alerts_active", "ingestion_alerts", ["is_active"], unique=False)
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("triggered_by", sa.String(length=50), nullable=False),
        sa.Column("records_ingested", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ingestion_runs_started_at", "ingestion_runs", ["started_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ingestion_runs_started_at", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index("idx_ingestion_alerts_active", table_name="ingestion_alerts")
    op.drop_table("ingestion_alerts")
    op.drop_index("idx_billing_usage_date", table_name="billing_records")
    op.drop_index("idx_billing_subscription", table_name="billing_records")
    op.drop_index("idx_billing_service_name", table_name="billing_records")
    op.drop_index("idx_billing_resource_group", table_name="billing_records")
    op.drop_table("billing_records")
    # ### end Alembic commands ###
