"""add_recommendations_table

Revision ID: e7846b8acf35
Revises: 37031473bbfa
Create Date: 2026-02-21 16:35:48.715390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7846b8acf35'
down_revision: Union[str, Sequence[str], None] = '37031473bbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.Column('resource_name', sa.String(length=500), nullable=False),
    sa.Column('resource_group', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('meter_category', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.String(length=2000), nullable=False),
    sa.Column('estimated_monthly_savings', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('current_monthly_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendation_category', 'recommendations', ['category'], unique=False)
    op.create_index('idx_recommendation_generated_date', 'recommendations', ['generated_date'], unique=False)
    op.create_index('idx_recommendation_resource', 'recommendations', ['resource_name', 'resource_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recommendation_resource', table_name='recommendations')
    op.drop_index('idx_recommendation_generated_date', table_name='recommendations')
    op.drop_index('idx_recommendation_category', table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
